### ISSUE TITLE
garbled ansi codes, --no-color does nothing

### ISSUE THREAD

**Issue by substack** [dominictarr/readme#12]
I just reinstalled debian and now I'm getting this output from `readme`:

![sc](http://scratch.substack.net/screenshot/2015-07-28-182454_721x483_scrot.png)

With `--no-color` I get the same output. My $PAGER is `less`.

**Comment by eush77** [comment]
Should be fixed now in 0.4.1.

In 0.4.1 colors are enabled by default only if the pager supports them (`$PAGER` is `less` and `$LESS` contains `-r` or `-R`) and `--[no-]color` switch is handled here rather than relying on `supports-color` somewhere in dependency tree.

You can set `LESS="-R"` in your bashrc and `less` will always interpret color sequences by default (it can also be controlled in runtime with the `-` command).

Thanks!

**Comment by substack** [comment]
Cool, didn't know that about $LESS. Thanks for the quick fix.
